# Create a client
# @name createClient
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "j@j.com"
}

###

# Save the client id to use in the next requests
@clientId = {{createClient.response.body.id}}

# Create another client
# @name createAnotherClient
POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "j@j.com"
}

###

# Save the client id to use in the next requests
@anotherClientId = {{createAnotherClient.response.body.id}}

###

# Create client account
# @name createClientAccount
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "{{clientId}}"
}

###

# Save the client id to use in the next requests
@clientAccountId = {{createClientAccount.response.body.id}}

###

# Create client account
# @name createAnotherClientAccount
POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id": "{{anotherClientId}}"
}


# Save the client id to use in the next requests
@anotherClientAccountId = {{createAnotherClientAccount.response.body.id}}

###

# Create transaction
# @name createTransaction
POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "{{clientAccountId}}",
  "account_id_to": "{{anotherClientAccountId}}",
  "amount": 50.00
}