POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "3042df27-9b79-4317-b5c6-d8959b8ee82a",
  "account_id_to": "44dc0fc5-2615-4cd1-94c6-88e26d465935",
  "amount": 50.0
}
